apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - services.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: atm-rul-prediction
